### ISSUE TITLE
Auto-publish gem using the interscript-ci user

### ISSUE THREAD

**Issue by ronaldtse** [interscript/iso-15924#5]
API key available in secrets and also added gem owner. Need GHA workflow to publish gem.

**Comment by ronaldtse** [comment]
Secret is under `INTERSCRIPT_RUBYGEMS_API_KEY`.

**Comment by webdev778** [comment]
Fix by this commit [f9ec8ba](https://github.com/interscript/iso-15924/commit/f9ec8ba2149d0171d6c1fbb3c1d1e7ac61a2c780)

**Comment by webdev778** [comment]
2149d0171d6c1fbb3c1d1e7ac61a2c780
